const IFX = [
    'Punch',
    'Overdrive ',
    'Distortion ',
    'Decimator ',
    'Bit Crusher ',
    'Ring Modulator ',
    'Sustainer ',
    'Limiter ',
    'Low EQ',
    'Mid EQ',
    'High EQ',
    'Radio EQ',
    'Exciter',
    'Low Pass Filter',
    'High Pass Filter',
    'Band Plus Filter',
    'Talk Filter',
    'Delay 1/4',
    'Delay 3/16',
    'Delay 1/8',
    'Delay 1/16',
    'Roller 1/32',
    'One Delay',
    'Short Delay',
    'Ring Delay 1',
    'Ring Delay 2',
    'Chorus',
    'Flanger LFO',
    'Flanger +',
    'Flanger -',
    'Phaser LFO 1',
    'Phaser LFO 2',
    'Phaser Manual',
    'Tremolo',
    'Off Beater',
    'Pumper',
    'Repeater',
    'Slicer',
];
