export const MOD = [
    {
        name: 'EG+ Filter',
        source: 'AD Envelope (positive)',
        destination: 'Filter Cutoff',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG+ Pitch',
        source: 'AD Envelope (positive)',
        destination: 'Oscillator Pitch',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG+ OSC',
        source: 'AD Envelope (positive)',
        destination: 'Oscillator Edit',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG+ Level',
        source: 'AD Envelope (positive)',
        destination: 'Amp Level',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG+ Pan',
        source: 'AD Envelope (positive)',
        destination: 'Pan',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG+ IFX',
        source: 'AD Envelope (positive)',
        destination: 'IFX Edit',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG+ BPM Filter',
        source: 'AD Envelope (positive)',
        destination: 'Filter Cutoff',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'EG+ BPM Pitch',
        source: 'AD Envelope (positive)',
        destination: 'Oscillator Pitch',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'EG+ BPM OSC',
        source: 'AD Envelope (positive)',
        destination: 'Oscillator Edit',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'EG+ BPM Level',
        source: 'AD Envelope (positive)',
        destination: 'Amp Level',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'EG+ BPM Pan',
        source: 'AD Envelope (positive)',
        destination: 'Pan',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'EG+ BPM IFX',
        source: 'AD Envelope (positive)',
        destination: 'IFX Edit',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'EG- Filter',
        source: 'AD Envelope (negative)',
        destination: 'Filter Cutoff',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG- Pitch',
        source: 'AD Envelope (negative)',
        destination: 'Oscillator Pitch',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG- OSC',
        source: 'AD Envelope (negative)',
        destination: 'Oscillator Edit',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG- Level',
        source: 'AD Envelope (negative)',
        destination: 'Amp Level',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG- Pan',
        source: 'AD Envelope (negative)',
        destination: 'Pan',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG- IFX',
        source: 'AD Envelope (negative)',
        destination: 'IFX Edit',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'EG- BPM Filter',
        source: 'AD Envelope (negative)',
        destination: 'Filter Cutoff',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'EG- BPM Pitch',
        source: 'AD Envelope (negative)',
        destination: 'Oscillator Pitch',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'EG- BPM OSC',
        source: 'AD Envelope (negative)',
        destination: 'Oscillator Edit',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'EG- BPM Level',
        source: 'AD Envelope (negative)',
        destination: 'Amp Level',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'EG- BPM Pan',
        source: 'AD Envelope (negative)',
        destination: 'Pan',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'EG- BPM IFX',
        source: 'AD Envelope (negative)',
        destination: 'IFX Edit',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'LFOTri Filter',
        source: 'LFO (triangle)',
        destination: 'Filter Cutoff',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'LFOTri Pitch',
        source: 'LFO (triangle)',
        destination: 'Oscillator Pitch',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'LFOTri OSC',
        source: 'LFO (triangle)',
        destination: 'Oscillator Edit',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'LFOTri Level',
        source: 'LFO (triangle)',
        destination: 'Amp Level',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'LFOTri Pan',
        source: 'LFO (triangle)',
        destination: 'Pan',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'LFOTri IFX',
        source: 'LFO (triangle)',
        destination: 'IFX Edit',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'LFOTriB Filter',
        source: 'LFO (triangle)',
        destination: 'Filter Cutoff',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'LFOTriB Pitch',
        source: 'LFO (triangle)',
        destination: 'Oscillator Pitch',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'LFOTriB OSC',
        source: 'LFO (triangle)',
        destination: 'Oscillator Edit',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'LFOTriB Level',
        source: 'LFO (triangle)',
        destination: 'Amp Level',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'LFOTriB Pan',
        source: 'LFO (triangle)',
        destination: 'Pan',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'LFOTriB IFX',
        source: 'LFO (triangle)',
        destination: 'IFX Edit',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawUpB Filter',
        source: 'LFO (up-saw)',
        destination: 'Filter Cutoff',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawUpB Pitch',
        source: 'LFO (up-saw)',
        destination: 'Oscillator Pitch',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawUpB OSC',
        source: 'LFO (up-saw)',
        destination: 'Oscillator Edit',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawUpB Level',
        source: 'LFO (up-saw)',
        destination: 'Amp Level',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawUpB Pan',
        source: 'LFO (up-saw)',
        destination: 'Pan',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawUpB IFX',
        source: 'LFO (up-saw)',
        destination: 'IFX Edit',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawDwnB Filter',
        source: 'LFO (down-saw)',
        destination: 'Filter Cutoff',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawDwnB Pitch',
        source: 'LFO (down-saw)',
        destination: 'Oscillator Pitch',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawDwnB OSC',
        source: 'LFO (down-saw)',
        destination: 'Oscillator Edit',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawDwnB Level',
        source: 'LFO (down-saw)',
        destination: 'Amp Level',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawDwnB Pan',
        source: 'LFO (down-saw)',
        destination: 'Pan',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SawDwnB IFX',
        source: 'LFO (down-saw)',
        destination: 'IFX Edit',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquUpB Filter',
        source: 'LFO (up-square)',
        destination: 'Filter Cutoff',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquUpB Pitch',
        source: 'LFO (up-square)',
        destination: 'Oscillator Pitch',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquUpB OSC',
        source: 'LFO (up-square)',
        destination: 'Oscillator Edit',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquUpB Level',
        source: 'LFO (up-square)',
        destination: 'Amp Level',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquUpB Pan',
        source: 'LFO (up-square)',
        destination: 'Pan',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquUpB IFX',
        source: 'LFO (up-square)',
        destination: 'IFX Edit',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquDwnB Filter',
        source: 'LFO (down-square)',
        destination: 'Filter Cutoff',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquDwnB Pitch',
        source: 'LFO (down-square)',
        destination: 'Oscillator Pitch',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquDwnB OSC',
        source: 'LFO (down-square)',
        destination: 'Oscillator Edit',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquDwnB Level',
        source: 'LFO (down-square)',
        destination: 'Amp Level',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquDwnB Pan',
        source: 'LFO (down-square)',
        destination: 'Pan',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'SquDwnB IFX',
        source: 'LFO (down-square)',
        destination: 'IFX Edit',
        bpmSync: true,
        keySync: true,
    },
    {
        name: 'S&HBPM Filter',
        source: 'LFO (sample & hold)',
        destination: 'Filter Cutoff',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'S&HBPM Pitch',
        source: 'LFO (sample & hold)',
        destination: 'Oscillator Pitch',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'S&HBPM OSC',
        source: 'LFO (sample & hold)',
        destination: 'Oscillator Edit',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'S&HBPM Level',
        source: 'LFO (sample & hold)',
        destination: 'Amp Level',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'S&HBPM Pan',
        source: 'LFO (sample & hold)',
        destination: 'Pan',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'S&HBPM IFX',
        source: 'LFO (sample & hold)',
        destination: 'IFX Edit',
        bpmSync: true,
        keySync: false,
    },
    {
        name: 'Random Filter',
        source: 'LFO (random)',
        destination: 'Filter Cutoff',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'Random Pitch',
        source: 'LFO (random)',
        destination: 'Oscillator Pitch',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'Random OSC',
        source: 'LFO (random)',
        destination: 'Oscillator Edit',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'Random Level',
        source: 'LFO (random)',
        destination: 'Amp Level',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'Random Pan',
        source: 'LFO (random)',
        destination: 'Pan',
        bpmSync: false,
        keySync: false,
    },
    {
        name: 'Random IFX',
        source: 'LFO (random)',
        destination: 'IFX Edit',
        bpmSync: false,
        keySync: false,
    },
];
